version: '3'

services:
  app1:
    security_opt:
      - apparmor=unconfined
    build: .  
    environment:
      - APP_NAME=application1
    ports:
      - "3001:3000" 
      
  app2:
    build: .
    environment:
      - APP_NAME=application2
    ports:
      - "3002:3000"

  app3:
    build: .
    environment:
      - APP_NAME=application3
    ports:
      - "3003:3000"
